import 'package:shopping_app/models/product.dart';

class MyProducts {
  static List<Product> laptops = [
    Product(
      id: 1,
      title: 'Apple MacBook Pro 14 Inch Space Grey',
      description: 'The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple\'s M1 Pro chip for exceptional performance and a stunning Retina display.',
      category: 'laptops',
      price: 165999,
      discountPercentage: 5,
      rating: 4.65,
      brand: 'Apple',
      warrantyInformation: '3 year warranty',
      shippingInformation: 'Ships in 2 weeks',
      availabilityStatus: 'In Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/1.webp',
        'https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/2.webp',
        'https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/3.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp',
    ),
    Product(
      id: 2,
      title: 'Asus Zenbook Pro Dual Screen Laptop',
      description: 'The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.',
      category: 'laptops',
      price: 149399,
      discountPercentage: 11,
      rating: 4.42,
      brand: 'Asus',
      warrantyInformation: '3 year warranty',
      shippingInformation: 'Ships in 1 month',
      availabilityStatus: 'In Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/1.webp',
        'https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/2.webp',
        'https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/3.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/laptops/asus-zenbook-pro-dual-screen-laptop/thumbnail.webp',
    ),
    Product(
      id: 3,
      title: 'New DELL XPS 13 9300 Laptop',
      description: 'The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks.',
      category: 'laptops',
      price: 124499,
      discountPercentage: 12,
      rating: 4.51,
      brand: 'Dell',
      warrantyInformation: '2 year warranty',
      shippingInformation: 'Ships in 2 weeks',
      availabilityStatus: 'In Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/1.webp',
        'https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/2.webp',
        'https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/3.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/laptops/new-dell-xps-13-9300-laptop/thumbnail.webp',
    ),
  ];

  static List<Product> smartphones = [
    Product(
      id: 4,
      title: 'iPhone 13 Pro',
      description: 'The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display. It offers advanced features for users who demand top-notch technology.',
      category: 'smartphones',
      price: 91299,
      discountPercentage: 9,
      rating: 4.67,
      brand: 'Apple',
      warrantyInformation: '3 year warranty',
      shippingInformation: 'Ships in 2 weeks',
      availabilityStatus: 'In Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/1.webp',
        'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/2.webp',
        'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/3.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp',
    ),
    Product(
      id: 5,
      title: 'iPhone X',
      description: 'The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance. It represents a milestone in iPhone design and innovation.',
      category: 'smartphones',
      price: 74699,
      discountPercentage: 20,
      rating: 4.28,
      brand: 'Apple',
      warrantyInformation: '3 months warranty',
      shippingInformation: 'Ships in 3-5 business days',
      availabilityStatus: 'In Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/smartphones/iphone-x/1.webp',
        'https://cdn.dummyjson.com/product-images/smartphones/iphone-x/2.webp',
        'https://cdn.dummyjson.com/product-images/smartphones/iphone-x/3.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp',
    ),
    Product(
      id: 6,
      title: 'Samsung Galaxy S10',
      description: 'The Samsung Galaxy S10 is a flagship device featuring a dynamic AMOLED display, versatile camera system, and powerful performance. It represents innovation and excellence in smartphone technology.',
      category: 'smartphones',
      price: 58099,
      discountPercentage: 6,
      rating: 4.35,
      brand: 'Samsung',
      warrantyInformation: 'No warranty',
      shippingInformation: 'Ships in 2 weeks',
      availabilityStatus: 'In Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/1.webp',
        'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/2.webp',
        'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/3.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/thumbnail.webp',
    ),
  ];

  static List<Product> tablets = [
    Product(
      id: 7,
      title: 'iPad Mini 2021 Starlight',
      description: 'The iPad Mini 2021 in Starlight is a compact and powerful tablet from Apple. Featuring a stunning Retina display, powerful A-series chip, and a sleek design, it offers a premium tablet experience.',
      category: 'tablets',
      price: 41499,
      discountPercentage: 4,
      rating: 4.48,
      brand: 'Apple',
      warrantyInformation: '2 year warranty',
      shippingInformation: 'Ships in 1-2 business days',
      availabilityStatus: 'In Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/1.webp',
        'https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/2.webp',
        'https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/3.webp',
        'https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/4.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/thumbnail.webp',
    ),
    Product(
      id: 8,
      title: 'Samsung Galaxy Tab S8 Plus Grey',
      description: 'The Samsung Galaxy Tab S8 Plus in Grey is a high-performance Android tablet by Samsung. With a large AMOLED display, powerful processor, and S Pen support, it\'s ideal for productivity and entertainment.',
      category: 'tablets',
      price: 49799,
      discountPercentage: 13,
      rating: 4.62,
      brand: 'Samsung',
      warrantyInformation: '3 months warranty',
      shippingInformation: 'Ships in 2 weeks',
      availabilityStatus: 'In Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/1.webp',
        'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/2.webp',
        'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/3.webp',
        'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/4.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-s8-plus-grey/thumbnail.webp',
    ),
    Product(
      id: 9,
      title: 'Samsung Galaxy Tab White',
      description: 'The Samsung Galaxy Tab in White is a sleek and versatile Android tablet. With a vibrant display, long-lasting battery, and a range of features, it offers a great user experience for various tasks.',
      category: 'tablets',
      price: 29049,
      discountPercentage: 18,
      rating: 4.15,
      brand: 'Samsung',
      warrantyInformation: '3 months warranty',
      shippingInformation: 'Ships overnight',
      availabilityStatus: 'In Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/1.webp',
        'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/2.webp',
        'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/3.webp',
        'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/4.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/tablets/samsung-galaxy-tab-white/thumbnail.webp',
    ),
  ];

  static List<Product> audiodevices = [
    Product(
      id: 10,
      title: 'Apple Airpods',
      description: 'The Apple Airpods offer a seamless wireless audio experience. With easy pairing, high-quality sound, and Siri integration, they are perfect for on-the-go listening.',
      category: 'audio',
      price: 10789,
      discountPercentage: 16,
      rating: 4.39,
      brand: 'Apple',
      warrantyInformation: '3 year warranty',
      shippingInformation: 'Ships in 3-5 business days',
      availabilityStatus: 'In Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/1.webp',
        'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/2.webp',
        'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/3.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp',
    ),
    Product(
      id: 11,
      title: 'Apple AirPods Max Silver',
      description: 'The Apple AirPods Max in Silver are premium over-ear headphones with high-fidelity audio, adaptive EQ, and active noise cancellation. Experience immersive sound in style.',
      category: 'audio',
      price: 45649,
      discountPercentage: 14,
      rating: 4.61,
      brand: 'Apple',
      warrantyInformation: 'No warranty',
      shippingInformation: 'Ships in 2 weeks',
      availabilityStatus: 'In Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/1.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp',
    ),
    Product(
      id: 12,
      title: 'Beats Flex Wireless Earphones',
      description: 'The Beats Flex Wireless Earphones offer a comfortable and versatile audio experience. With magnetic earbuds and up to 12 hours of battery life, they are ideal for everyday use.',
      category: 'audio',
      price: 4149,
      discountPercentage: 6,
      rating: 4.22,
      brand: 'Beats',
      warrantyInformation: '1 year warranty',
      shippingInformation: 'Ships in 1-2 business days',
      availabilityStatus: 'In Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/1.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp',
    ),
  ];

  static List<Product> accessories = [
    Product(
      id: 13,
      title: 'Apple Airpower Wireless Charger',
      description: 'The Apple AirPower Wireless Charger provides a convenient way to charge your compatible Apple devices wirelessly. Simply place your devices on the charging mat for effortless charging.',
      category: 'accessories',
      price: 6639,
      discountPercentage: 4,
      rating: 4.18,
      brand: 'Apple',
      warrantyInformation: '2 year warranty',
      shippingInformation: 'Ships in 1 week',
      availabilityStatus: 'Low Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/1.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp',
    ),
    Product(
      id: 14,
      title: 'Apple iPhone Charger',
      description: 'The Apple iPhone Charger is a high-quality charger designed for fast and efficient charging of your iPhone. Ensure your device stays powered up and ready to go.',
      category: 'accessories',
      price: 1659,
      discountPercentage: 19,
      rating: 4.45,
      brand: 'Apple',
      warrantyInformation: '1 year warranty',
      shippingInformation: 'Ships in 2 weeks',
      availabilityStatus: 'In Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/1.webp',
        'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/2.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp',
    ),
    Product(
      id: 15,
      title: 'Apple MagSafe Battery Pack',
      description: 'The Apple MagSafe Battery Pack is a portable and convenient way to add extra battery life to your MagSafe-compatible iPhone. Attach it magnetically for a secure connection.',
      category: 'accessories',
      price: 8299,
      discountPercentage: 17,
      rating: 4.33,
      brand: 'Apple',
      warrantyInformation: '2 year warranty',
      shippingInformation: 'Ships overnight',
      availabilityStatus: 'Low Stock',
      images: [
        'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/1.webp',
        'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/2.webp',
      ],
      thumbnail: 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp',
    ),
  ];

  static List<Product> allProducts = [
    ...laptops,
    ...smartphones,
    ...tablets,
    ...audiodevices,
    ...accessories,
  ];
}
